// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHh5S71gKMC8RCFHR2ovNwJ_a_oKuJ7ts',
    appId: '1:95771430312:web:c55ec8ddc5fe244951619d',
    messagingSenderId: '95771430312',
    projectId: 'eshop-6718a',
    authDomain: 'eshop-6718a.firebaseapp.com',
    storageBucket: 'eshop-6718a.firebasestorage.app',
    measurementId: 'G-LJCW2JZ55L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11ZYHMHy4LjmIx2EGByA7_uK1E-DtpQI',
    appId: '1:95771430312:android:beb5b22ad841ec9251619d',
    messagingSenderId: '95771430312',
    projectId: 'eshop-6718a',
    storageBucket: 'eshop-6718a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASFLUNhqawBMcRi9NgSCV91LHzwnFdNrA',
    appId: '1:95771430312:ios:3c4f3d584618ab6451619d',
    messagingSenderId: '95771430312',
    projectId: 'eshop-6718a',
    storageBucket: 'eshop-6718a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASFLUNhqawBMcRi9NgSCV91LHzwnFdNrA',
    appId: '1:95771430312:ios:3c4f3d584618ab6451619d',
    messagingSenderId: '95771430312',
    projectId: 'eshop-6718a',
    storageBucket: 'eshop-6718a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHh5S71gKMC8RCFHR2ovNwJ_a_oKuJ7ts',
    appId: '1:95771430312:web:81bd36432095343151619d',
    messagingSenderId: '95771430312',
    projectId: 'eshop-6718a',
    authDomain: 'eshop-6718a.firebaseapp.com',
    storageBucket: 'eshop-6718a.firebasestorage.app',
    measurementId: 'G-50HS4N6WWQ',
  );
}
